# Generated by Django 2.1.2 on 2018-10-23 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnumerateVariants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Fields',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=60)),
                ('enumerate', models.BooleanField()),
                ('enum_text', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='FieldTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='PolicyList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='RiskTypeList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
            ],
        ),
        migrations.AddField(
            model_name='policylist',
            name='risk_type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='risks.RiskTypeList'),
        ),
        migrations.AddField(
            model_name='fields',
            name='field_type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='risks.FieldTypes'),
        ),
        migrations.AddField(
            model_name='fields',
            name='risk_type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='risks.RiskTypeList'),
        ),
        migrations.AddField(
            model_name='enumeratevariants',
            name='field_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='risks.Fields'),
        ),
    ]
