# Generated by Django 2.1.2 on 2018-11-20 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('risks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enumeratevariants',
            name='field_id',
        ),
        migrations.DeleteModel(
            name='EnumerateVariants',
        ),
    ]
