# Generated by Django 2.1.2 on 2018-11-26 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('risks', '0002_auto_20181120_0909'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fieldvalue',
            name='field_type',
        ),
        migrations.DeleteModel(
            name='FieldValue',
        ),
    ]
