# Generated by Django 2.1.2 on 2018-10-25 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('risks', '0002_auto_20181024_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fields',
            name='risk_type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='risks.RiskTypeList'),
        ),
    ]
