# Generated by Django 2.1.2 on 2018-10-28 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risks', '0003_auto_20181025_0839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policylist',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
