# Generated by Django 2.1.2 on 2018-11-05 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risks', '0004_auto_20181028_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policylist',
            name='date',
            field=models.DateField(),
        ),
    ]
