# Generated by Django 2.1.2 on 2018-12-04 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('risks', '0004_fieldvalue'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldvalue',
            name='policie_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='risks.PolicyList'),
        ),
    ]
