# Generated by Django 2.1.2 on 2018-11-10 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risks', '0005_auto_20181105_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fields',
            name='enum_text',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
